apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:yQUq+ikPImjGXDf4hQNIzKCpagNNoVytlS8taymk5CQ6SUC44CxjmA1PBYOxel/LB52FfC5ZxUqMGFlIDwPq1QFPaEya/FFIsj6IbP8/tUIbb+ddauSm8zA9lwKvUl4LDpE1ATP3WhCh1aRlQx7F+1ISHdV9Qfaf6rwlsgmiq2LndL+fq4PAbPftCF8JxWscNZ8wbzWWUayWjdND/qi0k8pJGgxR8H+yZnhOYr2VEYkFstZFn8jsjO6FMkjB1PBsAo3sTovPQYNiUg0XCRuwrKYAXVgt+RQIKHTx15Nqu6+nHy9PFfq2hp+GvHw=,iv:kBcfqYbH7oigdOILb6qTwor4q5+a+EPALHSaTcvBDyk=,tag:pc9FMS8QSNiIAHr44beqOA==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
    namespace: audiobookshelf
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBma1MzVTcvZ1RFV3k4TVho
            ZWVJQTIxNTJpMmJCNVJpS1l6YmZwc29iYWtNCm45d25SUXdrZVBRUFJaSTBMWWVJ
            QnRkQW9IQzZ6MnRjcTEvQkprYzV2ZDQKLS0tIEtubEVPR2NMRUFtWERmR3pDclpU
            akFmRlJLOHBOZVpQZU1QdmdhSHpZMEUKmh+/V26QOx7eUNBBnRUHQpAjKVnKkvlc
            IFvhQAj49D5Dx0yZaUNeT+X0ZCNc3tq/lh6m36pOfLwNF1qpe79WdQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dvcx8ac3elyv53x5g0w2t6wucyvry8lttg0ync7wnrazc45dsa4q56889n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-11T09:32:49Z"
    mac: ENC[AES256_GCM,data:RF1nceZTVp67w4YdD6aybDd+qR0177wAFzYdwSiL+0IfYWp9OI6mKjWRMbsM/cLuUVao+NTS4nBCXSR429b2wHgWFtKg7E/98Nr/RIkumVJXFEySjO7GCEgc66VUDro5Acsx41U6ysE93LbtXqMYuo/wGOP2z5kQCeHmkzqJN2Q=,iv:WkjEGK/LboRepkdP34/AsSROk7soAZjjEnikMdIde9A=,tag:FdCtmhUapetGGvo15atsLw==,type:str]
    version: 3.13.3
