apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:zffGQ3n6Fa1pCd8+QDc54h7LuvcEwidsWqf3s96LtbcXkz1a7pA7hPMquSqzQqVqA3vDkTq9NKw6hv8HzrtfWnwoTF2g4zYVWRkw34MDV/tbg2CfSb+zn+DQeHqYYkBley7NkyT0BkZAhxREpPXghlPR/KK0S7DXUqWcaGjw+d+nKSrYhBlFC03711SiFGWEb3szlE3q9ru8kPNO+wHFFoberEuxkXP1O60KJiDsPf3OEtZee5s/vizpATokqlc508i4tRVz7t7LFFP/MNriaZ9Q8TUhy6LrSflY4qK1xwsT3UQX5Jmjgh51pRE=,iv:3GlA8WLhVkareljjhXdjPQv2OGMkoes1U7xNRXAniCk=,tag:jzERUrJS1BSut7Fdg+c/9g==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvRmZVM1dkV1liUytWZm91
            cjlrR1E1OXhLdG9BVktJcmNTc2U4TmhRTlJzCjltZ1YyTzZReDVKR2pmMHVCUXoz
            b2N2Y0JDV3JmaC82NjdVZTBwaTlWVkUKLS0tIERwSHUrRi9Mb0ZkcHVXUlFUWkJT
            aXNuUTJFcjZlYzFqbFJ5amRyZ09CK0UK0w13jHbAla1nulDBNU+Jrro/Z94a/Fr3
            S0RgiJgW2btK06w2XogMetG3X5g/ZGeeXNk6wIRvAENw7OaHfMjCtQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dvcx8ac3elyv53x5g0w2t6wucyvry8lttg0ync7wnrazc45dsa4q56889n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-06T12:25:11Z"
    mac: ENC[AES256_GCM,data:KtXxhsaJb36ktWKogTMdidb+4XPKGO1SDC4auzyUsRrlAvWw/qyxRKfTlNHCaxNQ+/ydUnXnEdvP9fBhawxcTxoaDYeNsc8rBFLseNHsf3FU9XE7G+ltDR67GGW17ZCr5Y2b1CJB7AEnfHDBhA0FHjXQUhJRPEfx24JSectGxR8=,iv:dWTuX7zSwuvRFr/jZrnCGkW5bjhldAm3sEbqwmFyd78=,tag:GnmNfF0R9xirkCGWRFBC6A==,type:str]
    version: 3.13.3
