apiVersion: v1
data:
    password: ENC[AES256_GCM,data:SMruS08FO3Q=,iv:Vp7aSu4kZk8tIQESzyjedaF7Gqay+w3tS9ggRd14Qyw=,tag:t/EIlil6/ERb7HZlYOzb1w==,type:str]
    user: ENC[AES256_GCM,data:hIlJVBEX0BQ=,iv:G1UOud2CxyKvSMHzAwcdpCl/cGYitfkS6Vqgub8TnjY=,tag:HocVBo7uNphPQUZLPqCBgA==,type:str]
kind: Secret
metadata:
    name: test-secret
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEWXhTNE9saWppWmJvbFNq
            bnRRNmU4d3N1WjZOSW9xb0xHQXRZbDdQV0dZCitZS09xeW9JY3NndGJpYU1pNmpv
            NldBNjA4TThiaU4vNnBSVXhkQ01oc2MKLS0tIERvNHZvRkFnYVdzUjR1alFoVEJI
            RGVlMGdVL3V2NG1MdVZ1cGRhNTFOblEKlw+SCuE8ahAGxVw6X43TZ3BqNndHUiHd
            z1+BwTJ0rYIex43sULDsWbQgQICtGGrEnVFxzoRACQV1u253WTF4LA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dvcx8ac3elyv53x5g0w2t6wucyvry8lttg0ync7wnrazc45dsa4q56889n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-06T05:52:28Z"
    mac: ENC[AES256_GCM,data:vIn4Xf+p9xiFwYmbv7xloDZ61CRUR4ZnhAj4GiTniKmVTTEa3CZygLmq2Jj72bxv+bswIGRpiMWgYZntjmD7JMR+FuFyciu7Hbjt79T6X8m80lDJWRpsaqybH8h9A+AjQ8ykj6VoLBIVe1q/c5QfGeOcKCyeormHUkERqsOZT4g=,iv:u5B1EjqnpRdS4H9FI9XkZEAT3BjhsD7d+lXLZ5Woii4=,tag:Ikei0VvMQDLn0DoBFFRUDQ==,type:str]
    version: 3.13.3
