apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio-frontend
  template:
    metadata:
      labels:
        app: portfolio-frontend
    spec:
      containers:
        - name: portfolio-frontend
          image: nithinu08/nithinhomepage-frontend:latest@sha256:04a3c4e04654bdab2dab738fa3be7f7b38ee4e5bafdd6a85c2c895f046d93b20
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "50m"
              memory: "32Mi"
            limits:
              memory: "64Mi"
