apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio-backend
  template:
    metadata:
      labels:
        app: portfolio-backend
    spec:
      containers:
        - name: portfolio-backend
          image: nithinu08/nithinhomepage-backend:latest@sha256:a3e879cc19d45335d7e0863de41ad9c43452d852b6d11bea08afbf5f38d568a1
          ports:
            - containerPort: 8080
          env:
            - name: OTEL_EXPORTER_ENDPOINT
              value: "signoz-otel-collector.signoz.svc.cluster.local:4317"
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              memory: "128Mi"
