apiVersion: v1
kind: Secret
metadata:
    name: tunnel-credentials
type: Opaque
stringData:
    credentials.json: ENC[AES256_GCM,data:p2a1qsVI2L6pGzpWhSd9eE8qprESExumYST72Er/kLl+QRd7ghgiOOQxvVO0HYWTcycnynFTCxuNnHK318C/I33ubRkRnY4xSDLZ9+kGkizG1boapolfbsoiTZ3KUK7wiCU0QDpQGe2jS77X20QoKcmad2q/7GEFSAq0hMaAvyBbbvO1lWyknm8jrQdLiGB08Com7Z7S5d0u0MELSMhMn/QShzLMADEwRVqAxa9XA4U=,iv:GwbzKVwVJu9Oa/C/JjSubkD3cp962RrfEtZ2bnnO+H8=,tag:ZQ7YO4KlWKmZHpPkb4aLJw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzbFJSNEYrSkovdFVVOEov
            TFFGYVpKZVpYWmNqTkcvVFFUbGVtQXdlQURrCi9OYmh5bUdzL3JqUFR3Nm5RV2Vq
            RXFrTVRrT3hsbXJlMUp2enpHUzNIYmMKLS0tIGhtVFYzUXFBczdibVp1ZkpYZG54
            Z0hITUlNTHRYTUp2azRzdFBVcU1sRDgKF01bJUoe0i3ZMXqje0ZoTBOIC4TqheoW
            Lok8OV+9xeOvxdHRXfWg3nGBTHtH5wPuOvD9DE9Ec+RWrhkU0GB8/g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dvcx8ac3elyv53x5g0w2t6wucyvry8lttg0ync7wnrazc45dsa4q56889n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-11T09:49:08Z"
    mac: ENC[AES256_GCM,data:0oCcTyFSh3r+x3RE7KAg5gyXOWtPgSHIUGHreK/SZWGnEA3MVLV/JllXYeqaMsw6XovLciCPgHM92nbcraGPLW1BODlvJoLNf/9MocaIBU8DI5Ky5MzLZnbNsWb1ApdapzqFhDhTQEYI7XobfJy3hkZEPhFd262MqrwrqhMHR6Y=,iv:qqZTxdqQ52cGGwV4Suu7iLe62bmdmhgU87rhcWb0/O8=,tag:mP7O3KWl2qJ6HB5ZJlYqJQ==,type:str]
    version: 3.13.3
