apiVersion: v1
data:
    admin-password: ENC[AES256_GCM,data:pJ/pt4ujwhSN0PAda+Cx7HGtmPN4h+D3cAxAE8XAd10uUPSwdZgCe8e1dYI=,iv:wRuDZUwX/Q1GUk/Gs9XoOGOC1aJLplNKcNB/m+18Hxk=,tag:naETiuyGWKjTzQBUE658+g==,type:str]
    admin-user: ENC[AES256_GCM,data:Yt82MqObdcE=,iv:RkMjVn5I/hbWlkSK9QtXzeWr/ZQxa6ZvnO8CNlOFxO0=,tag:AvlbIwjtF3ZnZUVOoxT3QQ==,type:str]
kind: Secret
metadata:
    name: grafana-admin
    namespace: monitoring
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCSVp0cHhpL0RWbU03LzRY
            ckl3L3B2a0V4UTB3QUZkRmdWdkVOMTVXd1gwCmFWZG9Va1ptQlpWaEdINFhWOEZJ
            bkZtbHlQMURQaUJMWDBCaysrQ1RTSm8KLS0tIGh2aFY5azR2TGVuK1U5eHRJbGtI
            VWl4OVpjRnByVjBpMThoT0ZZY0FwekEKiZLRmBoMSwkgk7SsA5PMkcWL51Qd+xtk
            Xs7ZcvdxWjhCBMWFacRm/FolUp/q7iYQh8jxr1BkER7eOukgemvGUg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dvcx8ac3elyv53x5g0w2t6wucyvry8lttg0ync7wnrazc45dsa4q56889n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-29T09:53:49Z"
    mac: ENC[AES256_GCM,data:OIA17A1adA6YeM8V2X0M8ImouLRCcK0O5Xo/oCo3Nt07lz90/lz6dxie3BnutvTOyZ1QDmHPFD0dwFB9ujjjqpE3Z5zqNK0YkRfWje2QNz1h+sUwDFJahrEVnQRicH5icDdPhOg6rb8lp/XkGWGg5I33Lq7Ai+qi/H1P37SEmtQ=,iv:I82GA2FLkrwC0rXKgI+P3aXPqASogVR+fXHmPjBxo+I=,tag:w+rt0jW4wKn8UjpxnCSVlA==,type:str]
    version: 3.13.3
